### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by Marthinius** [shashstormer/m3u8_proxy-cors#12]
Command:  pip install -r requirements.txt
**First Error:**

```
 If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for maturin
      Failed to build maturin
      ERROR: Could not build wheels for maturin, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
**So i installed rust** commnad: apt install rustc
_First error fixed but_

**SECOND Error:**

  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      Collecting maturin<2,>=1
        Using cached maturin-1.7.0.tar.gz (188 kB)
        Installing build dependencies: started
        Installing build dependencies: still running...
        Installing build dependencies: still running...
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting typing-extensions!=4.7.0,>=4.6.0
        Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
      Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
      Building wheels for collected packages: maturin
        Building wheel for maturin (pyproject.toml): started
        Building wheel for maturin (pyproject.toml): still running...
        Building wheel for maturin (pyproject.toml): still running...
        Building wheel for maturin (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for maturin (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [39 lines of output]
            /tmp/pip-build-env-g3dxoyvn/overlay/local/lib/python3.11/dist-packages/setuptools/config/_apply_pyprojecttoml.py:79: SetuptoolsWarning: `install_requires` overwritten in `pyproject.toml` (dependencies)
              corresp(dist, value, root_dir)
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-armv5tejl-cpython-311
            creating build/lib.linux-armv5tejl-cpython-311/maturin
            copying maturin/__main__.py -> build/lib.linux-armv5tejl-cpython-311/maturin
            copying maturin/__init__.py -> build/lib.linux-armv5tejl-cpython-311/maturin
            running egg_info
            creating maturin.egg-info
            writing maturin.egg-info/PKG-INFO
            writing dependency_links to maturin.egg-info/dependency_links.txt
            writing requirements to maturin.egg-info/requires.txt
            writing top-level names to maturin.egg-info/top_level.txt
            writing manifest file 'maturin.egg-info/SOURCES.txt'
            reading manifest file 'maturin.egg-info/SOURCES.txt'
            reading manifest template 'MANIFEST.in'
            warning: no files found matching '*.json' under directory 'src/python_interpreter'
            writing manifest file 'maturin.egg-info/SOURCES.txt'
            running build_ext
            running build_rust
                Updating crates.io index
            error: Unable to update registry `crates-io`

            Caused by:
              failed to fetch `https://github.com/rust-lang/crates.io-index`

            Caused by:
              network failure seems to have happened
              if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
              https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

            Caused by:
              SSL error: 0xffff8780 - SSL - The peer notified us that the connection is going to be closed; class=Ssl (16)
            error: `cargo metadata --manifest-path Cargo.toml --format-version 1 --locked` failed with code 101
            -- Output captured from stdout:

            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for maturin
      Failed to build maturin
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (maturin)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Second error not fixed...i try it....failed

**Comment by shashstormer** [comment]
What OS are you on 
What python version are you using

**Comment by shashstormer** [comment]
also where did you install your python from

**Comment by Marthinius** [comment]
OS:                    Debian 12
Python3 Version: 3.11.2
Python install via terminal: apt install python3

**Comment by shashstormer** [comment]
Can you try using a python 3.9 environment preferably from anaconda as "pyproject.toml-based projects" have a lot of problems with newer python versions

As i have originally made it with python 3.9 and newer version compatibility is not checked.

**Comment by shashstormer** [comment]
Closing this issue as other people have recently deployed various commits of this proxy and it has successfully worked, If you need more support you can contact shashstormer on discord (or reopen this issue).
