### ISSUE TITLE
It doesn't work with nginx proxy manager 

### ISSUE THREAD

**Issue by lucius100** [shashstormer/m3u8_proxy-cors#6]
If I just use direct url with my server IP, it works fine.
But If I tried to replace server ip with my domain using nginx proxy manager, it doesn't work,  does there any additional settings I need to tweak ?
Because I don't want to directly expose my server ip and want to use my domain name.

**Comment by shashstormer** [comment]
No there are no additional settings you need to tweak. If you have set origins variable then set your domain also if you have not used it then there is no other setting that matters.
 
Things you should check:
-> The domain is configured properly to the server ip
-> What port are the requests going to default of this is 5010
-> Check your server's firewall settings to ensure that traffic on the port you're using for the proxy is allowed
-> If you're using HTTPS, verify that your SSL/TLS certificates are correctly configured and that there are no errors in your Nginx SSL configuration
-> If you're using a GUI like Nginx Proxy Manager, double-check the proxy settings there. Make sure that the domain is correctly associated with the proxy host and port.
-> Check Nginx error logs (/var/log/nginx/error.log) for any error messages that might provide clues about what's going wrong.
-> After making changes to the configuration, remember to restart Nginx for the changes to take effect

**Comment by shashstormer** [comment]
You should have an Nginx server block (usually located in /etc/nginx/sites-available/) that configures Nginx to act as a reverse proxy. The configuration might look something like this:

nginx
`server {
    listen 80;
    server_name your_domain.com;

    location / {
        proxy_pass http://localhost:5010;  # Assuming FastAPI is running on port 5010
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Additional SSL/TLS settings if you're using HTTPS
    # ...

    # Additional security and performance optimizations
    # ...
}`

After making changes to your Nginx configuration, restart Nginx to apply the changes

**Comment by lucius100** [comment]
> No there are no additional settings you need to tweak. If you have set origins variable then set your domain also if you have not used it then there is no other setting that matters in this case.
> 
> Things you should check: -> The domain is configured properly to the server ip -> What port are the requests going to, default of this proxy is 5010 -> Check your server's firewall settings to ensure that traffic on the port you're using for the proxy is allowed -> If you're using HTTPS, verify that your SSL/TLS certificates are correctly configured and that there are no errors in your Nginx SSL configuration -> If you're using a GUI like Nginx Proxy Manager, double-check the proxy settings there. Make sure that the domain is correctly associated with the proxy host and port. -> Check Nginx error logs (/var/log/nginx/error.log) for any error messages that might provide clues about what's going wrong. -> After making changes to the configuration, remember to restart Nginx for the changes to take effect -> also open browser's developer console to check for any specific error messages when accessing your domain.

Maybe I put origin variable before and forget to remove it, do you have any blocked m3u8 files url I can use for testing ?

**Comment by shashstormer** [comment]
No, but you can just scrape one easily. Also keep in mind that not all m3u8
require to use proxy.
