### ISSUE TITLE
可以直接将多个url提前放入main文件中然后调用吗。

### ISSUE THREAD

**Issue by hkthomas** [shashstormer/m3u8_proxy-cors#7]
类似nginx的反代location 路径匹配。
比如 http://localhost:5010/cors?id=1  id=2，然后直接调用。
因为如果同时访问多个url且是固定的话这样比较方便，可以同时访问多个，不用运行多个程序，每次访问都输一遍。

**Comment by shashstormer** [comment]
是的，你可以做到这一点，为此你可以输入 id 而不是 url，如“http://localhost:5010/cors?url=1”，并在“main”文件顶部创建一个字典，如 url_dictionary= {'1': "https://example.com/...", ...}
在其中预定义 url，以便您可以执行 `url_dictionary[url]` 在这种情况下，url 是您作为参数传递的 url 的 id

**Comment by hkthomas** [comment]
感谢解惑。

**Comment by hkthomas** [comment]
抱歉老兄，我不太懂这个，再次请教，我按照你说的在main文件顶部增加了url_dictionary = {'1': "https://example.com/**.m3u8"} 
然后访问 http://localhost:5010/cors?url=1 网页反馈500错误。
控制台输出 requests.exceptions.InvalidSchema: No connection adapters were found for '://1?'
我还需要在哪里插入url_dictionary吗？

**Comment by shashstormer** [comment]
You have mentioned the port which seems to be causing a issue you will need to look for a workaround
