### ISSUE TITLE
Custom domain

### ISSUE THREAD

**Issue by gabinfinity** [shashstormer/m3u8_proxy-cors#8]
Hi. I tried to setting up a custom domain with cloudflare, but i got error. Always return Bad Request, on localhost works fine.

**Comment by gabinfinity** [comment]
I tried with cloudflare and i still getting cors error, so i tried with serveo (https://serveo.net/) and i got bad request. Only directly from VPS IP or localhost works

For cloudflare i use Cloudflare Tunnels and Serveo uses SSH, both have SSL, and my encryption mode is Full

**Comment by shashstormer** [comment]
I see, there must be no issue as i am using cloudflare dns+proxy and encryption mode Full and it is working fine, 
https://cros.shashstorm.in/cors?url=https://gogocdn.net/cover/alice-to-therese-no-maboroshi-koujou-1692067047.png
https://cros.shashstorm.in/cors?url=https://anitaku.to/home.html

**Comment by gabinfinity** [comment]
Are you using vercel?

I didn't configure the environment variables because the documentation says it's not necessary. And I'm using Windows, I believe it's not possible to do this configuration. Wouldn't it be better to remove this from the code? Is it possible to block external access via cloudflare

**Comment by gabinfinity** [comment]
![image](https://github.com/shashstormer/m3u8_proxy-cors/assets/59806981/944f78df-9798-48bd-b677-35da21d21920)
https://python.braflix.app/

**Comment by shashstormer** [comment]
the env config is not necessary

i believe that your isp/firewall may be blocking from other computer accessing your pc

`I believe it's not possible to do this configuration. Wouldn't it be better to remove this from the code?` what do you mean?

Is it possible to block external access via cloudflare? 

i dont understand what you want to ask. if you want to block a particular ip/ ip from certain regions you can do it with cloudflare.

**Comment by gabinfinity** [comment]
i think after a lot request it is crashing, my site have a lot access and i would like to change my C# proxy to yours in Python. But its cashing. I restarted the proxy server and it back to work

**Comment by shashstormer** [comment]
ok so no issue now?

**Comment by gabinfinity** [comment]
if i added it to my site, it goes down again

**Comment by shashstormer** [comment]
then it might be ur vps provider issue as no one ever reported such issue to me and even i have quiet a lot of traffic and my instance has been running from the day of the last commit to the repo and it works without any issue.

**Comment by shashstormer** [comment]
your deployment works perfectly fine right now 

https://python.braflix.app/cors?url=https://anitaku.to

contact your vps provider if such issue occurs again as it does not seem to be an issue related to proxy and is a hosting issue

**Comment by shashstormer** [comment]
@gabinfinity Why did you use my proxy instance...
I have disabled it now
